### PR TITLE
Add robotiq driver

### PR DESCRIPTION
**Pull request by MarqRazz**

### CODE REVIEW

**Comment by JafarAbdi** [comment]
The new launch file could be tested with `ros2 launch kortex2_bringup kortex.launch.py robot_type:=gen3 robot_ip:=yyy.yyy.yyy.yyy use_fake_hardware:=true`

**Comment by MarqRazz** [comment]
@JafarAbdi do you get these errors when you plan with the gripper group?

```
[move_group-1] [moveit_move_group_default_capabilities.move_action_capability]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[move_group-1] [moveit_move_group_capabilities_base.move_group_capability]: Using planning pipeline 'move_group'
[move_group-1] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'gripper' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - gripper/gripper: Starting planning with 1 states already in datastructure
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - gripper/gripper: Starting planning with 1 states already in datastructure
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - gripper/gripper: Starting planning with 1 states already in datastructure
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - gripper/gripper: Starting planning with 1 states already in datastructure
[move_group-1] [moveit.ompl_planning.constrained_goal_sampler]: More than 80% of the sampled goal states fail to satisfy the constraints imposed on the goal sampler. Is the constrained sampler working correctly?
[move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint satisfied:: Joint name: 'finger_joint', actual value: 0.799996, desired value: 0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100
[move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint violated:: Joint name: 'left_inner_finger_joint', actual value: -0.799996, desired value: 0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100
[move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint satisfied:: Joint name: 'left_inner_knuckle_joint', actual value: 0.799996, desired value: 0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100
[move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint satisfied:: Joint name: 'right_inner_knuckle_joint', actual value: 0.799996, desired value: 0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100
[move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint satisfied:: Joint name: 'right_outer_knuckle_joint', actual value: 0.799996, desired value: 0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100
[move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint satisfied:: Joint name: 'right_inner_finger_joint', actual value: -0.799996, desired value: -0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:253 - gripper/gripper: Unable to sample any valid states for goal tree
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - gripper/gripper: Created 1 states (1 start + 0 goal)
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:253 - gripper/gripper: Unable to sample any valid states for goal tree
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - gripper/gripper: Created 1 states (1 start + 0 goal)
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:253 - gripper/gripper: Unable to sample any valid states for goal tree
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - gripper/gripper: Created 1 states (1 start + 0 goal)
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:253 - gripper/gripper: Unable to sample any valid states for goal tree
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - gripper/gripper: Created 1 states (1 start + 0 goal)
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 0.020480 seconds
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:213 - gripper/gripper: Insufficient states in sampleable goal region
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:213 - gripper/gripper: Insufficient states in sampleable goal region
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:213 - gripper/gripper: Insufficient states in sampleable goal region
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:213 - gripper/gripper: Insufficient states in sampleable goal region
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000185 seconds
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:213 - gripper/gripper: Insufficient states in sampleable goal region
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:213 - gripper/gripper: Insufficient states in sampleable goal region
[move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000083 seconds
[move_group-1] [moveit.ompl_planning.model_based_planning_context]: Unable to solve the planning problem
[move_group-1] [moveit_move_group_default_capabilities.move_action_capability]: No motion plan found. No execution attempted.
[rviz2-3] [move_group_interface]: Planning request accepted
[rviz2-3] [move_group_interface]: Planning request aborted
[rviz2-3] [move_group_interface]: MoveGroupInterface::plan() failed or timeout reached
```

**Comment by JafarAbdi** [comment]
> @JafarAbdi do you get these errors when you plan with the gripper group?
> 
> ```
> [move_group-1] [moveit_move_group_default_capabilities.move_action_capability]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
> [move_group-1] [moveit_move_group_capabilities_base.move_group_capability]: Using planning pipeline 'move_group'
> [move_group-1] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'gripper' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - gripper/gripper: Starting planning with 1 states already in datastructure
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - gripper/gripper: Starting planning with 1 states already in datastructure
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - gripper/gripper: Starting planning with 1 states already in datastructure
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:220 - gripper/gripper: Starting planning with 1 states already in datastructure
> [move_group-1] [moveit.ompl_planning.constrained_goal_sampler]: More than 80% of the sampled goal states fail to satisfy the constraints imposed on the goal sampler. Is the constrained sampler working correctly?
> [move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint satisfied:: Joint name: 'finger_joint', actual value: 0.799996, desired value: 0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100
> [move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint violated:: Joint name: 'left_inner_finger_joint', actual value: -0.799996, desired value: 0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100
> [move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint satisfied:: Joint name: 'left_inner_knuckle_joint', actual value: 0.799996, desired value: 0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100
> [move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint satisfied:: Joint name: 'right_inner_knuckle_joint', actual value: 0.799996, desired value: 0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100
> [move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint satisfied:: Joint name: 'right_outer_knuckle_joint', actual value: 0.799996, desired value: 0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100
> [move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint satisfied:: Joint name: 'right_inner_finger_joint', actual value: -0.799996, desired value: -0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:253 - gripper/gripper: Unable to sample any valid states for goal tree
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - gripper/gripper: Created 1 states (1 start + 0 goal)
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:253 - gripper/gripper: Unable to sample any valid states for goal tree
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - gripper/gripper: Created 1 states (1 start + 0 goal)
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:253 - gripper/gripper: Unable to sample any valid states for goal tree
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - gripper/gripper: Created 1 states (1 start + 0 goal)
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:253 - gripper/gripper: Unable to sample any valid states for goal tree
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:354 - gripper/gripper: Created 1 states (1 start + 0 goal)
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 0.020480 seconds
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:213 - gripper/gripper: Insufficient states in sampleable goal region
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:213 - gripper/gripper: Insufficient states in sampleable goal region
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:213 - gripper/gripper: Insufficient states in sampleable goal region
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:213 - gripper/gripper: Insufficient states in sampleable goal region
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000185 seconds
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:213 - gripper/gripper: Insufficient states in sampleable goal region
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:213 - gripper/gripper: Insufficient states in sampleable goal region
> [move_group-1] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000083 seconds
> [move_group-1] [moveit.ompl_planning.model_based_planning_context]: Unable to solve the planning problem
> [move_group-1] [moveit_move_group_default_capabilities.move_action_capability]: No motion plan found. No execution attempted.
> [rviz2-3] [move_group_interface]: Planning request accepted
> [rviz2-3] [move_group_interface]: Planning request aborted
> [rviz2-3] [move_group_interface]: MoveGroupInterface::plan() failed or timeout reached
> ```

Yes, but when I plan again it finds a solution successfully

**Comment by MarqRazz** [comment]
I get the same behavior. Do you think it's because we are expecting this joint to have a positive position?
`[move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint violated:: Joint name: 'left_inner_finger_joint', actual value: -0.799996, desired value: 0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100`

**Comment by JafarAbdi** [comment]
> I get the same behavior. Do you think it's because we are expecting this joint to have a positive position?
> `[move_group-1] [moveit_kinematic_constraints.kinematic_constraints]: Constraint violated:: Joint name: 'left_inner_finger_joint', actual value: -0.799996, desired value: 0.800000, tolerance_above: 0.000100, tolerance_below: 0.000100`

Can you test the latest commit I just pushed .?

**Comment by MarqRazz** [comment]
That fixed it, thanks for tracking it down!

**Comment by JafarAbdi** [comment]
Rebased on master

**Review by AndyZe — APPROVED** [review]
LGTM. The type of controller for the gripper may need to change soon, but that can be a followup PR.

**Comment by aalmrad** [comment]
Claude is analyzing this issue and will attempt an automated fix. A pull request will be opened if changes are made.

**Comment by aalmrad** [comment]
Claude is analyzing this issue and will attempt an automated fix. A pull request will be opened if changes are made.

**Comment by aalmrad** [comment]
Claude is analyzing this issue and will attempt an automated fix. A pull request will be opened if changes are made.

**Comment by aalmrad** [comment]
Claude is analyzing this issue and will attempt an automated fix. A pull request will be opened if changes are made.

**Comment by aalmrad** [comment]
Claude is analyzing this issue and will attempt an automated fix. A pull request will be opened if changes are made.

**Comment by aalmrad** [comment]
Claude is analyzing this issue and will attempt an automated fix. A pull request will be opened if changes are made.

**Comment by aalmrad** [comment]
Claude is analyzing this issue and will attempt an automated fix. A pull request will be opened if changes are made.

**Comment by aalmrad** [comment]
Claude has submitted a fix attempt: https://github.com/Kinovarobotics/ros2_kortex/pull/348

Please review the changes before merging.

**Pull request merged**
