### PR TITLE
Increase write() block time during mode switching

### PR DESCRIPTION
**Pull request by nbbrooks**
We think there may still be lingering commands from before controller mode switching was called, which then result in trying to servo after we have switched to a non servo mode, resulting in this error message

```
[ros2_control_node-1] [ERROR] [1631384286.114141171] [KortexMultiInterfaceHardware]: Kortex exception: Device error, Error sub type=WRONG_SERVOING_MODE => <srv: 3, fct: 1, msgType: 3>
[ros2_control_node-1] description: Wrong servoing mode, must be low level servoing mode
[ros2_control_node-1] [ERROR] [1631384286.114158213] [KortexMultiInterfaceHardware]: Error sub-code: WRONG_SERVOING_MODE
```
This attempts to fix this by
- Start blocking at start of prepare_command_mode_switch
- Increase blocking time from 50 to 200ms
- Use atomic for block_write

### CODE REVIEW

**Review by MarqRazz — APPROVED** [review]
Thanks for making the PR Nathan!

**Comment by schornakj** [comment]
I still ran into an exception while testing this. I'm wondering if it has to do with the initial state of the robot, though. It's a big log so I've attached it.
[pr_34_exception.txt](https://github.com/PickNikRobotics/ros2_kortex/files/7148615/pr_34_exception.txt)

End of the log:
```
[move_group-6] [INFO] [1631399842.028518937] [moveit_ros.trajectory_execution_manager]: Completed trajectory execution with status SUCCEEDED ...
[behavior_server_node-7] [INFO] [1631399842.053022815] [behavior_server_node.controller_switcher_module]: Switching controllers from `joint_trajectory_controller` to `streaming_controller`.
[ros2_control_node-1] [INFO] [1631399842.053117327] [KortexMultiInterfaceHardware]: Controller switch requested
[ros2_control_node-1] [INFO] [1631399842.626413060] [KortexMultiInterfaceHardware]: Switching to SINGLE_LEVEL_SERVOING
[behavior_server_node-7] [INFO] [1631399842.629104060] [behavior_server_node.behavior_tree.behavior_tree.tree_node]: Execution 'behaviors/MoveToNamedState' complete
[behavior_server_node-7] [INFO] [1631399842.629232137] [behavior_server]: Goal Succeeded
[ros2_control_node-1] terminate called after throwing an instance of 'Kinova::Api::KDetailedException'
[ros2_control_node-1]   what():  Device error, Error sub type=ROBOT_NOT_READY => <srv: 2, fct: 121, msgType: 3>
[ros2_control_node-1] description: Failed to execute twist command: Arm Break On In Progress
[ERROR] [ros2_control_node-1]: process has died [pid 137722, exit code -6, cmd '/home/picknik/ws_studio/install/controller_manager/lib/controller_manager/ros2_control_node --ros-args --params-file /tmp/launch_params_fu2jnr4j --params-file /home/picknik/ws_studio/install/kortex2_bringup/share/kortex2_bringup/config/kortex_controllers.yaml --params-file /tmp/launch_params_nl3wlzfa'].
```

**Comment by schornakj** [comment]
It was working well for a long time before then, though.

**Comment by nbbrooks** [comment]
Interesting. I'm starting on an architecture diagram of how control
switching works
https://docs.google.com/drawings/d/1s1R5O-sMtJrg1KmHyqzqZ9JaCm5tKD4Oi8Ce917WggI

But looking at this I notice 3 things.

1. Still getting the 2PI message. Not sure where it would be coming from
[ros2_control_node-1] [WARN] [1631384286.102698792]
[KortexMultiInterfaceHardware]: Arms joint[2] command error is too large,
setting command to current robot position. Error: 6.288112. Command:
3.146863, Actual: -3.141248

2. We are getting the same Kinova exception as before
[ros2_control_node-1] [ERROR] [1631384286.114141171]
[KortexMultiInterfaceHardware]: Kortex exception: Device error, Error sub
type=WRONG_SERVOING_MODE => <srv: 3, fct: 1, msgType: 3>
[ros2_control_node-1] description: Wrong servoing mode, must be low level
servoing mode
[ros2_control_node-1] [ERROR] [1631384286.114158213]
[KortexMultiInterfaceHardware]: Error sub-code: WRONG_SERVOING_MODE

followed by
[ros2_control_node-1] terminate called after throwing an instance of
'Kinova::Api::KDetailedException'
[ros2_control_node-1]   what():  Device error, Error sub
type=ROBOT_NOT_READY => <srv: 2, fct: 121, msgType: 3>
[ros2_control_node-1] description: Failed to execute twist command: Arm
Break On In Progress

At first glance this looks just like the other logs before any of the PRs.
You sure they are in the workspace? I saw some mentioned of weird dual
workspace setups.

**Comment by davetcoleman** [comment]
>  I saw some mentioned of weird dual workspace setups.

I consoildated colcon into one workspace this morning, so this shouldn't be an issue

**Comment by nbbrooks** [comment]
I'm taking a look again at this approach and because I block write at the beginning, it won't halt existing motion while the switching is occurring. Need to rethink this. I'm also taking a look at https://github.com/PickNikRobotics/ros2_kortex/pull/30

**Review by davetcoleman — APPROVED** [review]
This PR ended up running during competition 1, and the full system was the most reliable we've ever seen it. No segdaults or restarts required. So we're gonna keep this, please rework in future PRs as needed.

**Pull request merged**
