### PR TITLE
Use gripper through internal bus extension

### PR DESCRIPTION
**Pull request by livanov93**
PR info:

- enable parametrization of gripper communication

TODO:

- do appropriate actions regarding tool comm

### CODE REVIEW

**Comment by livanov93** [comment]
@MarqRazz Can you give me more context on the whole request regarding internal bus/other options for gripper communication. Direct me so I can adjust hardware interface appropriately.

**Comment by destogl** [comment]
@livanov93 since here is a ToDO, should we wait with reviewing/merging this?

**Comment by livanov93** [comment]
@destogl it can wait a bit, it needs more attention.

**Comment by livanov93** [comment]
@destogl Please review it now, it is ready.

**Review by destogl — APPROVED** [review]

**Pull request merged**
