### PR TITLE
Add import-token to action-ros-ci and trigger on main

### PR DESCRIPTION
**Pull request by moriarty**
This is hard to test locally.
Found this related issue: https://github.com/ros-tooling/action-ros-ci/issues/691

Also noticed jobs were not getting triggered because of the branch name change. Updated CI in this PR

### CODE REVIEW

**Comment by moriarty** [comment]
```
Invoking: bash -c,vcs import --force --recursive src/ --input https://raw.githubusercontent.com/PickNikRobotics/ros2_kortex/177926ad70529b786b8fd87e7915c6c48eba05a4/ros2_kortex.repos?token=***
  /usr/bin/bash -c vcs import --force --recursive src/ --input https://raw.githubusercontent.com/PickNikRobotics/ros2_kortex/177926ad70529b786b8fd87e7915c6c48eba05a4/ros2_kortex.repos?token=***
  HTTP Error 404: Not Found
Error: The process '/usr/bin/bash' failed with exit code 1
```

**Comment by moriarty** [comment]
```
  /home/runner/work/ros2_kortex/ros2_kortex/.work/upstream_ws/src/ros2_controllers/joint_trajectory_controller/src/joint_trajectory_controller.cpp:1043:30: error: ‘struct control_msgs::msg::JointTrajectoryControllerState_<std::allocator<void> >’ has no member named ‘feedback’
   1043 |       state_publisher_->msg_.feedback.accelerations = current_state.accelerations;
        |                              ^~~~~~~~
  /home/runner/work/ros2_kortex/ros2_kortex/.work/upstream_ws/src/ros2_controllers/joint_trajectory_controller/src/joint_trajectory_controller.cpp:1048:30: error: ‘struct control_msgs::msg::JointTrajectoryControllerState_<std::allocator<void> >’ has no member named ‘output’
   1048 |       state_publisher_->msg_.output = command_current_;
        |                              ^~~~~~
  gmake[2]: *** [CMakeFiles/joint_trajectory_controller.dir/build.make:76: CMakeFiles/joint_trajectory_controller.dir/src/joint_trajectory_controller.cpp.o] Error 1
  gmake[1]: *** [CMakeFiles/Makefile2:208: CMakeFiles/joint_trajectory_controller.dir/all] Error 2
  gmake: *** [Makefile:146: all] Error 2
  ---
  Failed   <<< joint_trajectory_controller [15.7s, exited with code 2]
  Aborted  <<< force_torque_sensor_broadcaster [27.8s]
  
  Summary: 14 packages finished [1min 29s]
    1 package failed: joint_trajectory_controller
    1 package aborted: force_torque_sensor_broadcaster
    8 packages had stderr output: controller_manager diff_drive_controller joint_state_broadcaster joint_trajectory_controller ros2_controllers_test_nodes ros2controlcli rqt_controller_manager rqt_joint_trajectory_controller
    17 packages not processed
'build_upstream_workspace' returned with code '2' after 1 min 29 sec
```

This is caused by the upstream breakage: https://github.com/ros-controls/control_msgs/pull/86

**Comment by moriarty** [comment]
The original issue 404 error is now fixed
```
Invoking: bash -c,vcs import --force --recursive src/ --input https://raw.githubusercontent.com/PickNikRobotics/ros2_kortex/177926ad70529b786b8fd87e7915c6c48eba05a4/ros2_kortex.repos?token=***
  /usr/bin/bash -c vcs import --force --recursive src/ --input https://raw.githubusercontent.com/PickNikRobotics/ros2_kortex/177926ad70529b786b8fd87e7915c6c48eba05a4/ros2_kortex.repos?token=***
  HTTP Error 404: Not Found
Error: The process '/usr/bin/bash' failed with exit code 1
```

```
Invoking: bash -c,vcs import --force --recursive src/ --input file:///home/runner/work/ros2_kortex/ros2_kortex/ros2_kortex.repos
  /usr/bin/bash -c vcs import --force --recursive src/ --input file:///home/runner/work/ros2_kortex/ros2_kortex/ros2_kortex.repos
```

Instead of pulling the file via https:// it is grabbed directly from the disk from the previous checkout step https://github.com/PickNikRobotics/ros2_kortex/pull/99/commits/12093e7227e14f8585c9c5dbafd15a99d811df3b

The token was needed for the next issue which we weren't running into because CI was failing earlier.

**Review by abake48 — APPROVED** [review]
Approved since the fixes to the JTC msgs are available upstream and aren't caused by this PR.

**Comment by moriarty** [comment]
image

I will disable the full source build it is too slow. But I merged this in because it had other fixes like turning CI on `main` instead of `master`

**Pull request merged**
