### PR TITLE
Specify MoveIt Planners to use

### PR DESCRIPTION
**Pull request by abake48**
Define MoveIt planners to use. This way, we can avoid trying to use Stomp in a version of ROS where it isn't available/released.

### CODE REVIEW

**Comment by moriarty** [comment]
That's a weird failure
```
  ERROR: the following rosdeps failed to install
    apt: command [apt-get install -y -qq ros-humble-rviz2] failed
  '( source /opt/ros/humble/setup.bash && rosdep install -q --from-paths /home/runner/work/ros2_kortex/ros2_kortex/.work/upstream_ws/src --ignore-src -y | grep -E '(executing command)|(Setting up)' ; )' returned with 1
'install_upstream_dependencies' returned with code '1' after 1 min 41 sec
```

**Comment by abake48** [comment]
This is such an odd error... is the apt package just `ros-rolling-rviz`, no 2?

**Comment by moriarty** [comment]
@abake48 this PR says no lines added no lines removed after you merged main into this PR, did something get lost or did something already get in via another PR?

**Comment by abake48** [comment]
Something must have gotten lost when the launch file refactor PR got merged. I'll update this PR to add `chomp` and `pilz` planner

**Review by moriarty — APPROVED** [review]
LGTM

**Pull request merged**
